# Generated by Django 2.2 on 2019-04-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='estate',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='propertyimage',
            old_name='estate',
            new_name='property',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='comment',
            field=models.TextField(max_length=642),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/default_user/default_user.jpg', upload_to='users/'),
        ),
    ]
